export enum RouteId {
  NONE = 'NONE',
  TITLE = 'TITLE',
  MAIN_MENU = 'MAIN_MENU',
  MODE_SELECT = 'MODE_SELECT',
  HUD = 'HUD',
  PAUSE_MODAL = 'PAUSE_MODAL',
  SETTINGS_OVERLAY = 'SETTINGS_OVERLAY',
  RESULTS_SCREEN = 'RESULTS_SCREEN',
  LEADERBOARD_SCREEN = 'LEADERBOARD_SCREEN',
  PROFILE_SCREEN = 'PROFILE_SCREEN',
  SHOP_SCREEN = 'SHOP_SCREEN',
}
