export enum SceneId {
  BOOTSTRAP = 'BOOTSTRAP',
  SPLASH = 'SPLASH',
  MAIN_MENU = 'MAIN_MENU',
  MODE_SELECTION = 'MODE_SELECTION',
  GAMEPLAY = 'GAMEPLAY',
  RESULTS = 'RESULTS',
  PROFILE = 'PROFILE',
  LEADERBOARD = 'LEADERBOARD',
  COSMETICS = 'COSMETICS',
  SETTINGS = 'SETTINGS',
}
