const fs = require('fs');
const path = require('path');

const gdosDir = path.join(__dirname, '..', 'FLOWSTATE_MASTER_GUIDE');
const governanceDir = path.join(gdosDir, 'GOVERNANCE');
const agentsPath = path.join(__dirname, '..', '.agents', 'AGENTS.md');

fs.mkdirSync(governanceDir, { recursive: true });

const universalYaml = (title, phase = "00.06") => `---
Title: "${title}"
Module: "GOVERNANCE"
Status: Active
Priority: Critical
Milestone: 1
Phase: "${phase}"
Spec Version: 1.0.0
Owner: Antigravity IDE / Codex
Dependencies: [98_CANON, 99_PROJECT_MEMORY, 00_PROJECT_CORE]
Provides: [AI Operational Rules & Repository Governance]
Blocks: [Phase 00.07, Implementation Phases]
Estimated Work: 4 hours
Difficulty: High
Breaking Change: No
Last Updated: 2026-07-23
---
`;

const governanceFiles = {
  'AI_OPERATING_RULES.md': `${universalYaml('AI Operating Rules')}
# AI Operating Rules & Execution Protocol

This document establishes the mandatory operating rules for Antigravity IDE, Codex, and all AI agents working on FLOWSTATE.

---

## Mandatory 13-Step AI Execution Workflow

\`\`\`mermaid
flowchart TD
    Step1[1. Read Canon: 98_CANON/] --> Step2[2. Read Memory: 99_PROJECT_MEMORY/]
    Step2 --> Step3[3. Read Constitution: 00_PROJECT_CORE/]
    Step3 --> Step4[4. Read Architecture Map: ARCHITECTURE_MAP.md]
    Step4 --> Step5[5. Inspect Repository Source Code]
    Step5 --> Step6[6. Create/Update Implementation Plan]
    Step6 --> Step7[7. Implement Code Modifications]
    Step7 --> Step8[8. Run Typecheck & Unit Tests]
    Step8 --> Step9[9. Benchmark Performance & Memory]
    Step9 --> Step10[10. Update GDOS Specifications]
    Step10 --> Step11[11. Update DECISION_LOG & CHANGELOG]
    Step11 --> Step12[12. Verify 10-Point AI Quality Gate]
    Step12 --> Step13[13. Mark Phase Complete]
\`\`\`

## Operating Rules
1. **Never Skip Memory**: Always check [MEMORY_PROTOCOL.md](../99_PROJECT_MEMORY/MEMORY_PROTOCOL.md) before proposing code modifications.
2. **Respect Protected Files**: Never mutate files listed in [Do_Not_Break_Rules.md](../00_PROJECT_CORE/Do_Not_Break_Rules.md).
3. **Verify Zero Errors**: Always run \`npm run typecheck\` before declaring a phase complete.
4. **Token Discipline**: Force usage of \`tokens.css\` variables for all UI styles.
`,

  'REPOSITORY_CONTRACT.md': `${universalYaml('Repository Contract')}
# Repository Contract & Workspace Boundaries

## Workspace Ownership Structure
- **\`frontend/\`**: WebGL 3D game client, Babylon.js rendering, UI screens, HUD, and physics solvers.
- **\`middleware/\`**: Node.js Express gateway and WebSocket sync services.
- **\`backend/\`**: Cloud functions, serverless API, and database schemas.
- **\`shared/\`**: Shared TypeScript types, vector math, and spline calculators.
- **\`FLOWSTATE_MASTER_GUIDE/\`**: AI-Native Game Development Operating System (GDOS). Primary Source of Truth.

## Folder Classifications
- **Protected Folders**: \`frontend/src/core/physics/\`, \`shared/math/\`
- **Generated Folders**: \`node_modules/\`, \`dist/\`, \`build/\`
- **Temporary Folders**: \`.system_generated/\`, \`scratch/\`
- **Governance Folders**: \`FLOWSTATE_MASTER_GUIDE/GOVERNANCE/\`, \`.agents/\`

## Rules of Engagement
- **Never Edit**: Generated bundles, vendor packages, or locked core physics solvers without formal ADR approval.
- **Always Inspect**: Inspect exact file definitions before dereferencing symbol parameters.
- **Allowed Modifications**: Spec files, UI screens, living world simulation modules, test suites.
- **Required Approvals**: Architectural changes require explicit User approval via Implementation Plan.
`,

  'MODIFICATION_POLICY.md': `${universalYaml('Modification Policy')}
# Modification Policy & File Classification

Every file in the FLOWSTATE repository falls into one of 6 modification categories:

| Category | Description | Modification Rules | Examples |
|---|---|---|---|
| **Immutable** | Core Canon & Laws | Never edit during code tasks; readable reference only | \`98_CANON/*\` |
| **Critical** | Core Physics & Spline Math | Requires ADR, user approval, and regression testing | \`movement-engine.ts\`, \`spline-calculator.ts\` |
| **Protected** | Design Tokens & System Schemas | Edits require backwards compatibility verification | \`tokens.css\`, \`movement-intent.ts\` |
| **Conditional** | UI Screens, Ecosystem, Audio | Edits allowed if 10-Point Quality Gate passes | \`player-hud.ts\`, \`environment-view.ts\` |
| **Safe** | GDOS Specs, Tests, Documentation | Free modification for task completion | \`FLOWSTATE_MASTER_GUIDE/*\`, \`*.test.ts\` |
| **Generated** | Build artifacts & node modules | Auto-generated by tools; do not manual edit | \`dist/*\`, \`package-lock.json\` |
`,

  'SAFE_EDITING_GUIDE.md': `${universalYaml('Safe Editing Guide')}
# Safe Editing Guide & Risk Prevention

## 1. Preventing Duplicate Systems
- Search \`REPOSITORY_KNOWLEDGE.md\` and codebase using \`grep_search\` before building new helper classes.
- Never re-implement vector spline calculations or token color lookups.

## 2. Preventing Breaking Architecture
- Never import UI controllers into core physics solvers.
- Communication must flow top-down or via read-only event dispatchers.

## 3. Preventing API & Contract Removal
- Do not delete interface properties marked \`readonly\`.
- Use \`Partial<T>\` or fallback defaults (\`?? 0\`) for optional parameters.

## 4. Preventing Performance Regressions & Memory Leaks
- Do not instantiate \`new Vector3()\` or \`new Array()\` inside \`render()\` or tick loops.
- Use static temporary vectors (\`Vector3.TEMP\`) or object pools.

## 5. Preventing Circular Dependencies
- Keep dependency tree strictly directed (\`shared\` $\\leftarrow$ \`core\` $\\leftarrow$ \`simulation\` $\\leftarrow$ \`ui\`).
`,

  'FILE_OWNERSHIP.md': `${universalYaml('File Ownership Matrix')}
# File Ownership Matrix

| Folder Path | Primary Purpose | Owner | Allowed Edits | Protected Files | Dependencies |
|---|---|---|---|---|---|
| **\`00_PROJECT_CORE/\`** | Engineering Constitution & Rules | GDOS Core | Yes (Documentation) | \`Do_Not_Break_Rules.md\` | None |
| **\`98_CANON/\`** | Immutable Creative Constitution | Creative Director | No (Immutable Reference) | All files | None |
| **\`99_PROJECT_MEMORY/\`** | Project Memory & Decision Log | System Memory | Yes (Log Updates) | \`DECISION_LOG.md\` | All Modules |
| **\`GOVERNANCE/\`** | AI Operational Rules & Contracts | Governance Lead | Yes (Governance Updates) | \`AI_OPERATING_RULES.md\` | Core / Canon |
| **\`frontend/src/core/\`** | Physics & Game Loop | Engine Core | Conditional | \`movement-engine.ts\` | \`shared/\` |
| **\`frontend/src/ui/\`** | HUD & Presentation | UI/UX Lead | Yes | None | \`tokens.css\` |
| **\`frontend/src/rendering/\`** | Babylon.js Shaders & Splats | Graphics Lead | Yes | None | \`05_ENVIRONMENT_RENDERING\` |
`,

  'BREAKING_CHANGE_PROTOCOL.md': `${universalYaml('Breaking Change Protocol')}
# Breaking Change Protocol

## Change Classifications & Protocols

### 1. Minor Change (Non-Breaking)
- **Scope**: Localized bug fix or internal refactor.
- **Protocol**: Standard implementation pass with 0-error typecheck.

### 2. Major Change (System Scope)
- **Scope**: Modifying public module interfaces or data models.
- **Protocol**: Update GDOS specs, log in \`CHANGELOG.md\`, and verify backwards compatibility.

### 3. Architectural Change (Breaking)
- **Scope**: Modifying core physics kinetics, spline math, or data flow paths.
- **Protocol**:
  1. Create ADR entry in \`ARCHITECTURAL_DECISIONS.md\`.
  2. Obtain explicit User approval via Implementation Plan.
  3. Include verified \`Rollback.md\` protocol.
  4. Perform regression test suite verification.
`,

  'PHASE_EXECUTION_WORKFLOW.md': `${universalYaml('Phase Execution Workflow')}
# Formal Phase Execution Workflow

Every implementation phase package (\`AGENT_PROMPTS/Phase_XX/\`) executes through 8 mandatory lifecycle stages:

1. **Repository Audit**: Inspect target codebase files and check \`Do_Not_Break_Rules.md\`.
2. **Planning**: Scaffold/update \`implementation_plan.md\` and request user review if architectural.
3. **Implementation**: Modify codebase adhering strictly to coding patterns and token rules.
4. **Testing**: Run \`npm run typecheck\` and automated unit test suites.
5. **Performance Verification**: Confirm 60 FPS target and 0-byte frame memory allocation.
6. **Documentation Update**: Update target GDOS specs, \`CHANGELOG.md\`, and \`DECISION_LOG.md\`.
7. **Quality Gate Check**: Verify all 10 points of the AI Quality Gate Checklist.
8. **Phase Completion**: Submit completed work package summary.
`,

  'AI_FAILURE_RECOVERY.md': `${universalYaml('AI Failure Recovery')}
# AI Failure Recovery Protocol

If an implementation phase fails or introduces build errors/performance regressions, execute the following protocol:

\`\`\`mermaid
flowchart TD
    Failure[Build Error / Regression Triggered] --> Rollback[1. Execute Rollback via git checkout]
    Rollback --> RootCause[2. Perform Root Cause Analysis]
    RootCause --> LogLesson[3. Log Failure in LESSONS_LEARNED.md]
    LogLesson --> UpdateDecision[4. Update Decision Log & Strategy]
    UpdateDecision --> Retry[5. Attempt Retry with Modified Strategy]
\`\`\`

## Recovery Steps
1. **Rollback Immediately**: Revert workspace changes using \`git checkout HEAD -- [files]\`. Do not stack band-aid patches over broken commits.
2. **Analyze Root Cause**: Inspect un-truncated error logs or stack trace files.
3. **Record Lesson**: Add failure entry to \`99_PROJECT_MEMORY/LESSONS_LEARNED.md\`.
4. **Adjust Strategy**: Refine phase prompt or implementation plan.
`,

  'VALIDATION_PIPELINE.md': `${universalYaml('Validation Pipeline')}
# Automated & Manual Validation Pipeline

Every phase output must pass through the 8-Stage Validation Pipeline before completion:

1. **Architecture Validation**: Decoupled tiers; zero circular dependencies.
2. **Performance Validation**: 60 FPS verified; $< 40$ draw calls.
3. **Memory Validation**: 0-byte frame allocation; $< 150 \\text{ MB}$ RAM.
4. **Gameplay Validation**: Momentum conservation verified; no physics jitter.
5. **Accessibility Validation**: Scrim contrast $> 7:1$; touch targets $\\ge 44\\text{px}$.
6. **Documentation Validation**: Specs, \`DECISION_LOG.md\`, and \`CHANGELOG.md\` updated.
7. **Regression Validation**: Protected core physics files untouched.
8. **Canon Compliance Check**: 100% compliant with 27 Gameplay Laws & 42 Anti-Patterns.
`,

  'MERGE_POLICY.md': `${universalYaml('Merge Policy')}
# Final Merge Policy

Before declaring any implementation phase merged or complete, Antigravity IDE / Codex MUST verify:

- [ ] **1. Build**: Workspace builds cleanly without errors.
- [ ] **2. Typecheck**: \`npm run typecheck\` returns 0 errors across all monorepo packages.
- [ ] **3. Lint**: Code passes linter checks cleanly.
- [ ] **4. Tests**: All unit tests pass cleanly (\`npm test\`).
- [ ] **5. Benchmarks**: Frame budget (16.67ms) and memory limits respected.
- [ ] **6. Specs**: Relevant GDOS specification documents updated.
- [ ] **7. Decision Log**: Architectural choices recorded in \`DECISION_LOG.md\`.
- [ ] **8. Changelog**: Workspace deltas documented in \`CHANGELOG.md\`.
- [ ] **9. Lessons Learned**: Discoveries logged in \`LESSONS_LEARNED.md\`.
- [ ] **10. Quality Gate**: All 10 points in [ENGINEERING_CONSTITUTION.md](../00_PROJECT_CORE/ENGINEERING_CONSTITUTION.md#10-master-10-point-ai-quality-gate-checklist) verified.
`
};

Object.entries(governanceFiles).forEach(([filename, content]) => {
  fs.writeFileSync(path.join(governanceDir, filename), content, 'utf8');
});

// Generate .agents/AGENTS.md as a derived summary of GOVERNANCE documents
const agentsContent = `# Repository Rules & Coding Conventions for FLOWSTATE

> **Notice**: This file is an operational summary automatically derived from the primary GDOS Governance Layer located in \`FLOWSTATE_MASTER_GUIDE/GOVERNANCE/\`. Refer to the Governance Layer for authoritative rules.

---

## 1. Primary Source of Truth & Governance Hierarchy
- **Master OS**: All design, engineering, and operational rules derive from \`FLOWSTATE_MASTER_GUIDE/\`.
- **Canon**: Creative rules are governed by [\`98_CANON/\`](../FLOWSTATE_MASTER_GUIDE/98_CANON/Game%20Identity.md).
- **Memory**: Decisions & history are logged in [\`99_PROJECT_MEMORY/\`](../FLOWSTATE_MASTER_GUIDE/99_PROJECT_MEMORY/DECISION_LOG.md).
- **Governance**: Operational rules reside in [\`GOVERNANCE/\`](../FLOWSTATE_MASTER_GUIDE/GOVERNANCE/AI_OPERATING_RULES.md).

---

## 2. UI & Design Token Discipline
- All user interface elements must use CSS variables defined in \`frontend/src/ui/styles/tokens.css\`.
- Hardcoding raw hex color values, inline arbitrary padding/margins, or un-tokenized font stacks in TypeScript files is strictly prohibited (Anti-Pattern #13).
- Text legibility over 3D WebGL scenes must be backed by dark background scrims (\`var(--flow-text-scrim)\`).

---

## 3. HUD Architecture & Separation of Concerns
- **Player HUD (\`PlayerHud\`)** and **Developer Telemetry Panel (\`DevPanel\`)** must remain strictly separated in both component structure and visual appearance.
- Player HUD elements must remain minimal, clean, and unobtrusive ("Luminous Minimalism").
- Technical data (FPS counters, raw position vectors, input intent values) must stay isolated inside \`DevPanel\`.

---

## 4. Preservation of Gameplay Code
- Frontend visual passes must NEVER mutate, rewrite, or bypass core movement physics, collision math, target evaluation logic, or session state.
- Component controllers must interact with gameplay systems strictly via read-only telemetry data and public events.

---

## 5. Mandatory AI Execution Protocol
Before making any code modifications, AI agents MUST follow the 13-step workflow in [\`GOVERNANCE/AI_OPERATING_RULES.md\`](../FLOWSTATE_MASTER_GUIDE/GOVERNANCE/AI_OPERATING_RULES.md):
1. Inspect \`98_CANON/\` and \`99_PROJECT_MEMORY/DECISION_LOG.md\`.
2. Inspect protected files listed in \`00_PROJECT_CORE/Do_Not_Break_Rules.md\`.
3. Verify zero circular dependencies and 0-byte frame allocations.
4. Verify all 10 points of the **Master AI Quality Gate Checklist** before closing a phase.
5. Execute \`npm run typecheck\` to verify 0 compilation errors.
`;

fs.writeFileSync(agentsPath, agentsContent, 'utf8');

// Update INDEX.md to reference GOVERNANCE files
const indexPath = path.join(gdosDir, 'INDEX.md');
let indexContent = fs.readFileSync(indexPath, 'utf8');

const governanceIndexBlock = `### Governance & Agent Operating System (\`GOVERNANCE/\`)
- [GOVERNANCE/AI_OPERATING_RULES.md](GOVERNANCE/AI_OPERATING_RULES.md) — Mandatory 13-step AI execution workflow.
- [GOVERNANCE/REPOSITORY_CONTRACT.md](GOVERNANCE/REPOSITORY_CONTRACT.md) — Workspace ownership & protected folders.
- [GOVERNANCE/MODIFICATION_POLICY.md](GOVERNANCE/MODIFICATION_POLICY.md) — 6 file modification categories & rules.
- [GOVERNANCE/SAFE_EDITING_GUIDE.md](GOVERNANCE/SAFE_EDITING_GUIDE.md) — Risk prevention & anti-regression guide.
- [GOVERNANCE/FILE_OWNERSHIP.md](GOVERNANCE/FILE_OWNERSHIP.md) — Top-level folder ownership matrix.
- [GOVERNANCE/BREAKING_CHANGE_PROTOCOL.md](GOVERNANCE/BREAKING_CHANGE_PROTOCOL.md) — Breaking change classification & approval protocol.
- [GOVERNANCE/PHASE_EXECUTION_WORKFLOW.md](GOVERNANCE/PHASE_EXECUTION_WORKFLOW.md) — 8-stage implementation phase lifecycle.
- [GOVERNANCE/AI_FAILURE_RECOVERY.md](GOVERNANCE/AI_FAILURE_RECOVERY.md) — Emergency failure recovery & rollback workflow.
- [GOVERNANCE/VALIDATION_PIPELINE.md](GOVERNANCE/VALIDATION_PIPELINE.md) — 8-stage automated & manual validation pipeline.
- [GOVERNANCE/MERGE_POLICY.md](GOVERNANCE/MERGE_POLICY.md) — Final pre-merge verification checklist.
`;

if (!indexContent.includes('### Governance & Agent Operating System')) {
  indexContent = indexContent.replace('## 2. Governance & Operational Layer', '## 2. Governance & Operational Layer\n\n' + governanceIndexBlock);
  fs.writeFileSync(indexPath, indexContent, 'utf8');
}

// Update ROADMAP.md to track Phase 00.06 completion
const roadmapPath = path.join(gdosDir, 'ROADMAP.md');
let roadmapContent = fs.readFileSync(roadmapPath, 'utf8');

roadmapContent = roadmapContent.replace('| **Phase 00.06** | AI Operating Rules & Generate `.agents/AGENTS.md` | Planned |', '| **Phase 00.06** | AI Operating Rules & Generate `.agents/AGENTS.md` | ✅ Complete |');

fs.writeFileSync(roadmapPath, roadmapContent, 'utf8');

console.log('Phase 00.06 AI Governance & AGENTS.md scaffolded successfully!');
